language: python
python:
  - "3.9"
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip
install:
  - pip install -U platformio
  - pio update
script:
  - pio run
before_deploy:
  - "cp .pio/build/teensy/firmware.hex teensy.hex"
  - "cp .pio/build/d1_mini/firmware.bin d1_mini.bin"
  - "cp .pio/build/d32/firmware.bin d32.bin"
deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  file:
    - "teensy.hex"
    - "d1_mini.bin"
    - "d32.bin"
  cleanup: false
  on:
    tags: true
