language: python
python:
  - "3.9"
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip
install:
  - pip install -U platformio
  - pio update
script:
  - pio run
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  before_deploy:
    - "cp .pio/build/teensy/firmware.hex teensy.hex"
    - "cp .pio/build/d1_mini/firmware.hex d1_mini.hex"
    - "cp .pio/build/d32/firmware.hex d32.hex"
  file:
    - "teensy.hex"
    - "d1_mini.hex"
    - "d32.hex"
  skip_cleanup: true
  on:
    tags: true
